apiVersion: v1
kind: Service
metadata:
  name: {{ include "stater-kit-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stater-kit-chart.name" . }}
    helm.sh/chart: {{ include "stater-kit-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "stater-kit-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
