# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 3000

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""
